### ISSUE TITLE
baidu support

### ISSUE THREAD

**Issue by anchxng** [gamer-gang/gamerbot-classic#13]
eggsplain the feature and anything else important
i want you to give me baidu feature i want to listen to chinese music pls pls pls xue hua piao piao bei feng xiao xiao
i also want to watch video of xi jinping

**Comment by Mootbing** [comment]
stop it you dim sum

**Comment by notrealn** [comment]
make a pr loser!!!!

**Comment by calico32** [comment]
we won't be implementing this ourselves, sounds like a seldom used feature

you can use youtube for videos
