### ISSUE TITLE
Th hypixel bedwars stat feature doesn't work anymore

### ISSUE THREAD

**Issue by yhu120121** [gamer-gang/gamerbot-classic#22]
When using $stats, it gives a "Error: getaddrinfo ENOTFOUND crafatar" 

steps to reproduce the behavior:
1. invite the bot
2. send command "$stats" or "$stats [any username]"
3.error

It usually gives a chart with all of the stats, but it doesn't anymore

**Comment by notrealn** [comment]
We're rewriting the bot because the code is kind of messy right now with some different library stuffs. This one will probably become deprecated soon, so we probably won't fix this.

**Comment by calico32** [comment]
bruh im fixing it
